- name: Install Nginx
  apt: pkg=nginx state=installed
  sudo: yes
  tags:
    - setup
    - nginx

- name: Remove default Nginx site config
  file: path=/etc/nginx/sites-enabled/default state=absent
  sudo: yes
  notify:
    - restart nginx
  tags: 
    - setup
    - nginx

- name: put nginx file in site-enabled
  template: src=plivo_nginx.conf.j2 dest=/etc/nginx/sites-enabled/plivo_nginx.conf mode=0644
  sudo: yes
  notify:
    - restart nginx
  tags:
    - setup
    - nginx
    - config

- name: Restart Nginx
  service: name=nginx state=restarted
  sudo: yes
  tags:
    - setup
    - nginx
    - config

